### ISSUE TITLE
Issue Vorlage erstellen

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos-Multiplayer#13]
Issue Vorlage für Github erstellen.

**Comment by crykn** [comment]
Folgendes wäre mein Vorschlag für eine Issue-Vorlage:

> **[Eine einleitende, kurze Beschreibung des Bugs]**
>
> ### Schritte zum Reproduzieren
> 1. [Erster Schritt]
> 2. [Zweiter Schritt]
> 3. [usw.]
>
> **Erwartetes Verhalten:** [Was als Verhalten erwartet wurde]
> **Tatsächliches Verhalten:** [Was tatsächlich passiert ist; falls notwendig gerne auch mit einem  Screenshot]
>
> ### Weitere Informationen
> [Informationen über das verwendete **Betriebssystem**, die verwendete **Softwareversion**, etc.]
> [Falls die Anwendung einen **Error-Log** generiert hat (_crash.log_), diesen bitte mit anhängen.]
> 
> ### Aufgaben 
> [Nur für Issues von Entwicklern; gibt eine Übersicht über alles, was zur Lösung des Problems notwendig ist]
> - [ ] Task 1
> - [ ] Task 2
> - [ ] Task 3

**Comment by JuKu** [comment]
Gerade für Bugs sollten wir die Vorlage aber noch deutlich detailierter ausarbeiten. OS, Grafikkarte usw.

**Comment by SupressWarnings** [comment]
# _[aussagekräftige Überschrift die bereits erste Hinweise gibt, was der Fehler ist]_

[kurze Beschreibung: was kann man schlecht in die anderen Punkte schreiben, ist aber wichtig für das Verständnis des Bugs; möglicherweise unterstützt mit Bildern/Videos]

## **Schritte zur Reproduktion**

1.  [Erster Schritt]
2.  [Zweiter Schritt]
3.  [etc.]

## **Systeminformationen**
**Software-Version:** [Version unserer Software]
**Betriebssystem:** [Betriebssystem und Version]
**Hardware:** [falls relevant, z. B.:
    -Grafikkarte: 
    -Prozessor: 
    -freier Speicherplatz: 
    -Arbeitsspeicher: 
]
**Error-Log**: [Falls vom Spiel/System ein Error-Log erstellt wurde oder eine Fehlermeldung ausgegeben wurde, hier anhängen]


## **Fehlerbeschreibung**

[Was ist passiert? Warum ist dies als Fehler zu werten? ]

### Was hat sich geändert?

[ggfs.: Was ist bisher immer an dieser Stelle passiert? Was hat sich verändert?]

**Comment by SupressWarnings** [comment]
erstmal unwichtig -> also vorerst wird auf diese Vorlagen zurückgegriffen
