### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos-Multiplayer#14]
@SquidSushi Willst du vllt. ein Logo für das Game erstellen, oder sollen wir einfach das alte wiederverwenden?

**Comment by crykn** [comment]
Auch wenn der Name des Spiels noch nicht abschließend entschieden ist, haben wir ein Logo für den bisherigen Namen: 
![Logo](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5aa5836828b4bc0013daf44d/125516c66e82c728ace21e0d46ec9b8e338b80bdb0bbef12fc0da3c5707975237952f07b32c9a138ad4d71040c1b5ca6535d0e15f9fedc2df4e36821880f5fedd16c0b70c33b19a8ba9003ad43eb7edf10d8eff6df0ed2e22f24e0818e4a3c1c041e8dfd5837a79a4cda15.png)

**Comment by JuKu** [comment]
@crykn Bitte schließe nur die Issues, die dir selbst zugewiesen sind oder bei denen du mit den zugewiesenen Personen Rücksprache gehalten hast.
@SquidSushi hat bisher nicht gesagt, dass das Logo final ist, oder irre ich mich?

**Comment by JuKu** [comment]
@crykn Ah Sry, hatte die Diskussion im Slack Channel übersehen.
