### ISSUE TITLE
Code Coverage Badge

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos-Multiplayer#15]
Es muss das Code Coverage Badge von codecov.io eingerichtet werden.

**Comment by crykn** [comment]
Ist sie das nicht längst?

**Comment by JuKu** [comment]
@crykn Nein.
Codecov.io != Sonarcloud.

**Comment by crykn** [comment]
In der Beschreibung des Tickets steht allerdings "Code Coverage Badge von Sonarqube" und nicht "Codecov.io Badge". Und erstere ist ja bereits in der README eingebunden.

**Comment by JuKu** [comment]
@crykn Oh Sry!
Das war mein Fehler! Habe die Beschreibung entsprechend korrigiert.
