### ISSUE TITLE
Website-Zuständigkeit klären

### ISSUE THREAD

**Issue by SupressWarnings** [opensourcegamedev/SpaceChaos-Multiplayer#6]
Lars fragen, ob er weiter die Website wartet und bearbeitet und ggfs. andere Person benennen.

**Comment by JuKu** [comment]
@SupressWarnings Bitte ab sofort die Issues direkt in waffle.io erstellen. :D 

Lars kann sehr gerne die Webseite übernehmen / weiter verwalten, falls er Lust hat.
Frag ihn mal bitte, ob er das will oder nicht.

**Comment by JuKu** [comment]
@SupressWarnings Gibt es hier noch was zu klären oder können wir das Issue dann schließen?

**Comment by SupressWarnings** [comment]
Lars übernimmt weiter die Website
