### ISSUE TITLE
Vertx.io vs. KyroNet

### ISSUE THREAD

**Issue by JuKu** [opensourcegamedev/SpaceChaos-Multiplayer#7]
Entscheiden, ob wir Vertx.io oder KyroNet als Networking Engine verwenden.
https://github.com/EsotericSoftware/kryonet

**Comment by JuKu** [comment]
Der Backend Solution Architect würde Netty empfehlen. Allerdings ist Netty alleine ziemlich komplex, weshalb ich eine Abstraktion höher (vertx.io) gehen würde.

@crykn Da KyroNet nicht mehr aktiv weiter entwickelt wird (es gibt nur noch einen Comitter, der die letzten 3 Jahre 7 commits als Pull Request eingereicht hat) und damit nicht mit Java 9 kompatibel ist, würde ich gerne auf Vertx.io setzen.
Desweiteren habe ich mir den Source von KyroNet die letzten Tage genauer angesehen und ehrlich gesagt hat es mich nicht überzeugt.
1. setzt KyroNet auf Java Serialization, was in meinen Augen für Games überhaupt keine gute Performance bietet und unnötig Traffic verursacht, desweiteren arbeitet KyroNet nicht mit nativem Speicher, sondern mit On Heap Speicher --> ohne Off Heap Speicher wird uns der Server in die Knie gehen und 3. basiert dieser auf ganz einfachem Java NIO, kein Executor Service, nichts.
Zu guter letzt setzt KyroNet auch noch auf synchrone RMI Handler, was komplett den Thread blockt, während man auf eine Antwort wartet (--> extrem CPU intensiv). Beispiel:
https://github.com/EsotericSoftware/kryonet/blob/master/src/com/esotericsoftware/kryonet/rmi/RemoteObject.java

Aus diesen Gründen kann ich nur dringend von KyroNet abraten, dieses ist für kleine Multiplayer Spiele (vllt. bis 16 Spieler) ausgelegt, aber nicht mehr. Wir müssen aber mehrere Game Instanzen gleichzeitig bedienen, da geht uns KyroNet ohne Executor Service komplett in die Knie.
Aus diesem Grund gibt es schon Forks (z.B. KyroNetty), welche auf Netty basieren, allerdings wurden diese auch nicht weiter entwickelt.

Vertx.io kann wesentlich mehr als KyroNet, ist flexibler und aber auch genauso einfach zu nutzen. Es nutzt Executor Services (Thread Pools) und wird aktiv weiter entwickelt. Somit läuft es auch unter Java 9 noch und wird auch weiterhin aktiv supportet.

**Comment by crykn** [comment]
@JuKu 

> 1. setzt KyroNet auf Java Serialization

KryoNet setzt in erster Linie auf [Kryo](https://github.com/EsotericSoftware/kryo), daher auch der Name ;) Die Serialization ließe sich aber auch austauschen, so wird standardmäßig auch noch eine JSON-Serialization mitgeliefert.

>Zu guter letzt setzt KyroNet auch noch auf synchrone RMI Handler, was komplett den Thread blockt 

Das ist nur ein valider Kritikpunkt, wenn man auch RMI verwendet, wovon ich allerdings abraten würde. Einfacher ist es verschiedene Listener zu verwenden (bspw. ein [TypeListener](https://github.com/crykn/kryonet/blob/master/src/main/java/com/esotericsoftware/kryonet/Listener.java#L99) aus meine Fork, der teilt verschiedene Message-Klassen gleich komfortabel auf verschiedene Listener auf).

Aber wir können trotzdem sehr gerne auf vertx.io setzen! Letztlich kommen wir mit beiden zum Ziel.
