### ISSUE TITLE
Grundstruktur des Projektes erstellen

### ISSUE THREAD

**Issue by crykn** [opensourcegamedev/SpaceChaos-Multiplayer#9]
Die grundlegende Struktur des Projektes (ScreenManager, Game-Klasse, AssetLoading) hinzufügen.

**Comment by JuKu** [comment]
@crykn Der Titel dieses Issues ist etwas verwirrend, denn es handelt sich nicht um die "Struktur" (Artifacte, Module, Packages usw.), sondern direkt um Code.
